In [1]:
import numpy as np

def BasicGaussianElimination(A, b):
    n = len(b)
    for k in range(n-1):
        for i in range(k+1, n):
            if A[i, k] != 0.0:
                lam = A[i, k]/A[k, k]
                A[i, k+1:n] = A[i, k+1:n] - lam*A[k, k+1:n]
                b[i] = b[i] - lam*b[k]
    return A, b

def GaussianSwapForwardElimination(A, b):
    m, n = A.shape
    bn, = b.shape
    assert n == m == bn
    Aans = A.copy()
    bans = b.copy()
    l = list(range(n))
    sl = np.abs(A).max(axis=1)

    for k in range(n):
        for i in range(k+1, n):
            factor = Aans[i, k]/Aans[k, k]
            for j in range(k, n):
                Aans[i, j] = Aans[i, j] - factor*Aans[k, j]
            bans[i] = bans[i] - factor*bans[k]
            print(Aans, bans)
            print("----------------------------")


    return Aans, bans

def BackSubstitution(A, b):
    n = len(b)
    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(A[k, k+1:n], x[k+1:n]))/A[k, k]
    return x

def GaussianElimination(A, b):
#     A, b = BasicGaussianElimination(A, b)
    A, b = GaussianSwapForwardElimination(A, b)
    x = BackSubstitution(A, b)
    return x

if __name__ == '__main__':
    A = np.array([
        [6, -2, 2, 4], 
        [12, -8, 6, 10], 
        [3, -13, 9, 3],
        [-6, 4, 1, -18]
    ], float)
    b = np.array([16, 26, -19, -34], float)
    x = GaussianElimination(A, b)
    print(x)



[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]] [ 16.  -6. -19. -34.]
----------------------------
[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  0. -12.   8.   1.]
 [ -6.   4.   1. -18.]] [ 16.  -6. -27. -34.]
----------------------------
[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  0. -12.   8.   1.]
 [  0.   2.   3. -14.]] [ 16.  -6. -27. -18.]
----------------------------
[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  0.   0.   2.  -5.]
 [  0.   2.   3. -14.]] [ 16.  -6.  -9. -18.]
----------------------------
[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  0.   0.   2.  -5.]
 [  0.   0.   4. -13.]] [ 16.  -6.  -9. -21.]
----------------------------
[[ 6. -2.  2.  4.]
 [ 0. -4.  2.  2.]
 [ 0.  0.  2. -5.]
 [ 0.  0.  0. -3.]] [16. -6. -9. -3.]
----------------------------
[ 3.  1. -2.  1.]
