In [6]:
import numpy as np


def GaussianForwardElimination(A, b):
    m, n = A.shape
    bn, = b.shape
    assert n == m == bn
    Aans = A.copy()
    bans = b.copy()

    sl = np.abs(A).max(axis=1)

    def findMax(A, l, stepnum):
        ln = len(l)
        if stepnum >= ln-2:
            return
        r = np.array([abs(A[l[i]][stepnum])/sl[l[i]]
                     for i in range(stepnum, ln)])

        j = r.argmax() + stepnum
        print(A, l)
        l[stepnum] = l[j]
        l[j] = stepnum
        print(f"r = {r}, j = {j}, l = {l} -- Note l ที่ได้ ไม่ใช่ l คำตอบ ต้องเช็คกับ l ก่อนหน้าเพราะมันไม่ตรงกัน")
        print("--------------------------------------------------------")

    for k in range(n):
        l = list(range(n))
        findMax(A, l, k)
        for i in range(k+1, n):
            Qi = Aans[l[i]][k]/Aans[l[k]][k]
            for j in range(k, n):
                Aans[l[i]][j] -= Qi*Aans[l[k]][j]
            bans[l[i]] -= Qi*bans[l[k]]

    print(Aans, bans)
    print("--------------------------------------------------------")

    return Aans, bans


a = np.array([[3, -13, 9, 3],
              [-6, 4, 1, -18],
              [6, -2, 2, 4],
              [12, -8, 6, 10]], float)
b = np.array([-19, -34, 16, 26], float)

GaussianForwardElimination(a, b)


[[  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]
 [  6.  -2.   2.   4.]
 [ 12.  -8.   6.  10.]] [0, 1, 2, 3]
r = [0.23076923 0.33333333 1.         1.        ], j = 2, l = [2, 1, 0, 3] -- Note l ที่ได้ ไม่ใช่ l คำตอบ ต้องเช็คกับ l ก่อนหน้าเพราะมันไม่ตรงกัน
--------------------------------------------------------
[[  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]
 [  6.  -2.   2.   4.]
 [ 12.  -8.   6.  10.]] [0, 1, 2, 3]
r = [0.22222222 0.33333333 0.66666667], j = 3, l = [0, 3, 2, 1] -- Note l ที่ได้ ไม่ใช่ l คำตอบ ต้องเช็คกับ l ก่อนหน้าเพราะมันไม่ตรงกัน
--------------------------------------------------------
[[  0. -12.   8.   1.]
 [  0.   0.   4. -13.]
 [  6.   0.   1.   3.]
 [  0.  -4.   0.  -4.]] [-27. -21.  19. -44.]
--------------------------------------------------------


(array([[  0., -12.,   8.,   1.],
        [  0.,   0.,   4., -13.],
        [  6.,   0.,   1.,   3.],
        [  0.,  -4.,   0.,  -4.]]),
 array([-27., -21.,  19., -44.]))