In [4]:
import numpy as np


def LUdecomposition(A):
    m, n = A.shape
    U = A.copy()
    L = np.zeros_like(U)
    np.fill_diagonal(L, 1)


    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i]/U[i, i]
            U[j, i:] = U[j, i:] - L[j, i]*U[i, i:]

    return L, U

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
L, U = LUdecomposition(A)
print(f"Lower Matrix")
print(L)
print("----------------")
print(f"Upper Matrix")
print(U)


Lower Matrix
[[1 0 0]
 [4 1 0]
 [7 2 1]]
----------------
Upper Matrix
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]
