In [3]:
import numpy as np


def LUdecomposition(A):
    m, n = A.shape
    U = A.copy()
    L = np.zeros_like(U)
    np.fill_diagonal(L, 1)


    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i]/U[i, i]
            U[j, i:] = U[j, i:] - L[j, i]*U[i, i:]

    return L, U

A = np.array([[6, -2, 2, 4], [12, -8, 6, 10], [3, -13, 9, 3], [-6, 4, 1, -18]], dtype=np.float64)
L, U = LUdecomposition(A)
print(f"Lower Matrix")
print(L)
print("----------------")
print(f"Upper Matrix")
print(U)


Lower Matrix
[[ 1.   0.   0.   0. ]
 [ 2.   1.   0.   0. ]
 [ 0.5  3.   1.   0. ]
 [-1.  -0.5  2.   1. ]]
----------------
Upper Matrix
[[ 6. -2.  2.  4.]
 [ 0. -4.  2.  2.]
 [ 0.  0.  2. -5.]
 [ 0.  0.  0. -3.]]
